create database fender_basses_db;
use fender_basses_db;

create table basses (
    /* ID setup */
    id int auto_increment not null,
    primary key (id),

    /* The Fields */

    gen_brand varchar(50),
    gen_series varchar(50),
    gen_model varchar(100),

    gen_hand varchar(50),
    gen_signature tinyint(1),
    gen_type varchar(50),
    gen_country varchar(50),
    gen_firstYear int(4),
    gen_lastYear int(4),
    gen_era varchar(50),
    gen_market varchar(50),
    gen_marketingDesc text,
    gen_hardware varchar(50),
    gen_neckJoint varchar(50),
    gen_customShop tinyint(1),
    gen_modelNum varchar(50),
    gen_serialLoc varchar(50),
    gen_case varchar(50),
    gen_relic tinyint(1),
    gen_roadworn tinyint(1),
    gen_url varchar(500),
    gen_msrp decimal(7,2),
    gen_streetPrice decimal(7,2),
    gen_imageMain varchar(500),
    gen_imageObject varchar(500),

    neck_head_shape varchar(50),
    neck_head_strings tinyint(1),
    neck_head_tunerLayout varchar(50),
    neck_head_tunerHoleDiam varchar(50),

    neck_head_tuners_model varchar(50),
    neck_head_tuners_shape varchar(50),
    neck_head_tuners_baseSize varchar(50),
    neck_head_tuners_baseCover varchar(50),
    neck_head_tuners_finish varchar(50),
    neck_head_tuners_ratio varchar(50),
    neck_head_tuners_direction varchar(50),
    neck_head_tuners_postType varchar(50),
    neck_head_tuners_postDiameter varchar(50),

    neck_head_trees_number tinyint(1),
    neck_head_trees_type varchar(50),
    neck_head_trees_strings varchar(50),
    neck_head_trees_location varchar(50),
    neck_head_trees_finish varchar(50),
    neck_head_finishType varchar(50),
    neck_head_finishText varchar(50),
    neck_head_finishColor varchar(50),
    neck_head_brandLogoStyle varchar(50),
    neck_head_brandLogoColor varchar(50),
    neck_head_modelLogoStyle varchar(50),
    neck_head_modelLogoColor varchar(50),
    neck_head_nutStyle varchar(50),
    neck_head_nutMaterial varchar(50),
    neck_head_nutFinish varchar(50),
    neck_head_trussStyle varchar(50),
    neck_head_trussColor varchar(50),

    neck_neck_trussAdjDir varchar(50),
    neck_neck_trussLoc varchar(50),
    neck_neck_trussAdjType varchar(50),
    neck_neck_const varchar(50),
    neck_neck_wood varchar(50),
    neck_neck_skunk tinyint(1),
    neck_neck_skunkWood varchar(50),
    neck_neck_finishType varchar(50),
    neck_neck_finishText varchar(50),
    neck_neck_finishColor varchar(50),
    neck_neck_nutWidth decimal(3,2),
    neck_neck_heelWidth decimal(3,2),
    neck_neck_plateStyle varchar(50),
    neck_neck_plateFinish varchar(50),
    neck_neck_scale decimal(4,2),
    neck_neck_sideDotsStyle varchar(50),
    neck_neck_binding tinyint(1),
    neck_neck_bindingColor varchar(50),
    neck_neck_inlayShape varchar(50),
    neck_neck_inlayMaterial varchar(50),
    neck_neck_frets tinyint(1),
    neck_neck_fretboardMaterial varchar(50),
    neck_neck_slab tinyint(1),
    neck_neck_fretwireSize varchar(50),
    neck_neck_fretwireMaterial varchar(50),
    neck_neck_fretless tinyint(1),
    neck_neck_fretlessLines tinyint(1),
    neck_neck_fretlessEpoxy tinyint(1),
    neck_neck_radius decimal(4,2),
    neck_neck_heelShape varchar(50),
    neck_neck_shape varchar(50),
    neck_neck_depth varchar(50),
    neck_neck_overhang tinyint(1),
    neck_neck_rolledEdges varchar(50),

    body_wood varchar(50),
    body_color varchar(50),
    body_clear varchar(50),
    body_trussDivot tinyint(1),
    body_neckPool tinyint(1),
    body_middlePool tinyint(1),
    body_shape varchar(50),
    body_forearm tinyint(1),
    body_tummy tinyint(1),
    body_edgeRadius decimal(3,2),
    body_bridgeType varchar(50),
    body_bridgeModel varchar(50),
    body_bridgeFinish varchar(50),
    body_bridgeSaddle varchar(50),
    body_buttonType varchar(50),
    body_buttonFinish varchar(50),
    body_pg tinyint(1),
    body_pgShape varchar(50),
    body_pgMaterial varchar(50),
    body_pgColor varchar(50),
    body_pgScrewFinish varchar(50),
    body_controlPlate tinyint(1),
    body_controlPlateStyle varchar(50),
    body_controlPlateFinish varchar(50),
    body_elecMount varchar(50),
    body_jackLocation varchar(50),
    body_channelStyle varchar(50),
    body_jackPlate tinyint(1),
    body_jackPlateStyle varchar(50),
    body_jackPlateFinish varchar(50),
    body_knobStyle varchar(50),
    body_knobFinish varchar(50),
    body_batteryLocation varchar(50),
    body_chambering varchar(50),
    body_depth decimal(3,2),
    body_binding tinyint(1),
    body_bindingColor varchar(50),
    body_graphics tinyint(1),
    body_soundhole varchar(50),
    body_bridgeCover tinyint(1),
    body_pickupCover tinyint(1),
    body_mutes tinyint(1),
    body_thumbrest tinyint(1),
    body_tugBar tinyint(1),

    body_elec_neckPickupType varchar(50),
    body_elec_midPickupType varchar(50),
    body_elec_bridgePickupType varchar(50),
    body_elec_neckPickupModel varchar(50),
    body_elec_midPickupModel varchar(50),
    body_elec_bridgePickupModel varchar(50),
    body_elec_neckPickupFormat varchar(50),
    body_elec_middlePickupFormat varchar(50),
    body_elec_bridgePickupFormat varchar(50),
    body_elec_pickupColor varchar(50),
    body_elec_pickupPoles tinyint(1),
    body_elec_active tinyint(1),
    body_elec_knobConfig varchar(50),
    body_elec_switchConfig varchar(50),
    body_elec_pickupScrewFinish varchar(50),
    body_elec_potShaftStyle varchar(50),
    body_elec_groundingStrap tinyint(1)

)