insert into basses 
(

gen_brand,
gen_series,
gen_model,
gen_hand,
gen_signature,
gen_type,
gen_country,
gen_firstYear,
gen_lastYear,
gen_era,
gen_market,
gen_marketingDesc,
gen_hardware,
gen_neckJoint,
gen_customShop,
gen_modelNum,
gen_serialLoc,
gen_case,
gen_relic,
gen_roadworn,
gen_url,
gen_msrp,
gen_streetPrice,
gen_imageMain,
gen_imageObject,



neck_head_shape,
neck_head_strings,
neck_head_tunerLayout,
neck_head_tunerHoleDiam,

neck_head_tuners_model,
neck_head_tuners_shape,
neck_head_tuners_baseSize,
neck_head_tuners_baseCover,
neck_head_tuners_finish,
neck_head_tuners_ratio,
neck_head_tuners_direction,
neck_head_tuners_postType,
neck_head_tuners_postDiameter,

neck_head_trees_number,
neck_head_trees_type,
neck_head_trees_strings,
neck_head_trees_location,
neck_head_trees_finish,
neck_head_finishType,
neck_head_finishText,
neck_head_finishColor,
neck_head_brandLogoStyle,
neck_head_brandLogoColor,
neck_head_modelLogoStyle,
neck_head_modelLogoColor,
neck_head_nutStyle,
neck_head_nutMaterial,
neck_head_nutFinish,
neck_head_trussStyle,
neck_head_trussColor,

neck_neck_trussAdjDir,
neck_neck_trussLoc,
neck_neck_trussAdjType,
neck_neck_const,
neck_neck_wood,
neck_neck_skunk,
neck_neck_skunkWood,
neck_neck_finishType,
neck_neck_finishText,
neck_neck_finishColor,
neck_neck_nutWidth,
neck_neck_heelWidth,
neck_neck_plateStyle,
neck_neck_plateFinish,
neck_neck_scale,
neck_neck_sideDotsStyle,
neck_neck_binding,
neck_neck_bindingColor,
neck_neck_inlayShape,
neck_neck_inlayMaterial,
neck_neck_frets,
neck_neck_fretboardMaterial,
neck_neck_slab,
neck_neck_fretwireSize,
neck_neck_fretwireMaterial,
neck_neck_fretless,
neck_neck_fretlessLines,
neck_neck_fretlessEpoxy,
neck_neck_radius,
neck_neck_heelShape,
neck_neck_shape,
neck_neck_depth,
neck_neck_overhang,
neck_neck_rolledEdges,

body_wood,
body_color,
body_clear,
body_trussDivot,
body_neckPool,
body_middlePool,
body_shape,
body_forearm,
body_tummy,
body_edgeRadius,
body_bridgeType,
body_bridgeModel,
body_bridgeFinish,
body_bridgeSaddle,
body_buttonType,
body_buttonFinish,
body_pg,
body_pgShape,
body_pgMaterial,
body_pgColor,
body_pgScrewFinish,
body_controlPlate,
body_controlPlateStyle,
body_controlPlateFinish,
body_elecMount,
body_jackLocation,
body_channelStyle,
body_jackPlate,
body_jackPlateStyle,
body_jackPlateFinish,
body_knobStyle,
body_knobFinish,
body_batteryLocation,
body_chambering,
body_depth,
body_binding,
body_bindingColor,
body_graphics,
body_soundhole,
body_bridgeCover,
body_pickupCover,
body_mutes,
body_thumbrest,
body_tugBar,

body_elec_neckPickupType,
body_elec_midPickupType,
body_elec_bridgePickupType,
body_elec_neckPickupModel,
body_elec_midPickupModel,
body_elec_bridgePickupModel,
body_elec_neckPickupFormat,
body_elec_middlePickupFormat,
body_elec_bridgePickupFormat,
body_elec_pickupColor,
body_elec_pickupPoles,
body_elec_active,
body_elec_knobConfig,
body_elec_switchConfig,
body_elec_pickupScrewFinish,
body_elec_potShaftStyle,
body_elec_groundingStrap

) 
values 

(

"Fender",
"Custom Artist",
"Jaco Pastorius Tribute Jazz Bass",
"Right",
"1",
"Jazz",
"USA",
"2013",
"2018",
"FMIC",
"Worldwide",
"The Jaco Pastorius Tribute Jazz Bass® is a faithful re creation of the bass master’s famously distressed sunburst-finish fretless Jazz Bass, and is a result of meticulous research done in cooperation with his technician. Features include a select alder body, specially shaped maple neck, epoxy-coated fretless rosewood fingerboard and knurled chrome Precision Bass® control knobs.",
"Nickel/Chrome",
"Bolt-On",
"1",
"196108800",
"Neck Plate",
"Deluxe Hardshell",
"1",
"0",
"http://www.fendercustomshop.com/series/artist/jaco-pastorius-tribute-jazz-bass-rosewood-fingerboard-3-color-sunburst/",
"2499.99",
"1899.95",
"{ photo:”filepath.jpg”, caption:”This is the caption for the primary image.”, sourceText:”Website Name”, sourceLink:”http://www.websitename.com” }",
"{ { photo:”filepath2.png”, caption:”This is the caption for the second picture.”, sourceText:”Another Website Name”, sourceLink:”http://www.anothersitename.com” }, { photo:”filepath3.jpg”, caption:”This is the caption for pic 3.”, sourceText:”eBay”, sourceLink:”http://www.ebay.com” } }",



"Standard",
"4",
"4 Inline",
"9/16",

"American Vintage Reverse Open-Gear Bass",
"Elephant Ear",
"Large",
"Open",
"Nickel",
"4:1",
"Reverse",
"Split",
"9/16",

"1",
"Round",
"D-G",
"E-A",
"Nickel",
"Polyurethane",
"Gloss",
"Clear",
"Classic",
"Gold w/ Black Outline",
"Classic",
"Black",
"Standard",
"Synthetic Bone",
"NA",
"None",
"NA",

"Single Action",
"Heel",
"Hex Wrench",
"One Piece",
"Maple",
"1",
"Rosewood",
"Nitrocellulose Lacquer",
"Gloss",
"Clear",
"1.5",
"2.5",
"4-Bolt",
"Nickel",
"34",
"Black",
"0",
"NA",
"Dot",
"Clay",
"21",
"Rosewood",
"1",
"N/A",
"N/A",
"1",
"1",
"1",
"7.25",
"Round",
"C",
"Standard",
"0",
"Unknown",

"Alder",
"3-Color Sunburst",
"Nitrocellulose Lacquer",
"0",
"0",
"0",
"Jazz",
"1",
"1",
"0.5",
"Standard",
"4-Saddle American Vintage Bass",
"Nickel",
"Threaded",
"Standard",
"Nickel",
"0",
"NA",
"NA",
"NA",
"NA",
"1",
"Jazz",
"Nickel",
"Top",
"Control Plate",
"Tunnel",
"0",
"NA",
"NA",
"Knurled Flat-Top",
"Nickel",
"NA",
"Solid",
"1.75",
"0",
"NA",
"0",
"NA",
"0",
"0",
"0",
"0",
"0",

"Jazz",
"NA",
"Jazz",
"Custom '60s Single-Coil Jazz Bass®",
"NA",
"Custom '60s Single-Coil Jazz Bass®",
"Single Coil",
"NA",
"Single Coil",
"Black",
"1",
"0",
"VVT",
"NA",
"Chrome",
"Solid",
"1"

)

,

(

"Fender",
"Custom Artist",
"Jaco Pastorius Tribute Jazz Bass",
"Right",
"1",
"Jazz",
"USA",
"2013",
"2018",
"FMIC",
"Worldwide",
"The Jaco Pastorius Tribute Jazz Bass® is a faithful re creation of the bass master’s famously distressed sunburst-finish fretless Jazz Bass, and is a result of meticulous research done in cooperation with his technician. Features include a select alder body, specially shaped maple neck, epoxy-coated fretless rosewood fingerboard and knurled chrome Precision Bass® control knobs.",
"Nickel/Chrome",
"Bolt-On",
"1",
"196108800",
"Neck Plate",
"Deluxe Hardshell",
"1",
"0",
"http://www.fendercustomshop.com/series/artist/jaco-pastorius-tribute-jazz-bass-rosewood-fingerboard-3-color-sunburst/",
"2499.99",
"1899.95",
"{ photo:”filepath.jpg”, caption:”This is the caption for the primary image.”, sourceText:”Website Name”, sourceLink:”http://www.websitename.com” }",
"{ { photo:”filepath2.png”, caption:”This is the caption for the second picture.”, sourceText:”Another Website Name”, sourceLink:”http://www.anothersitename.com” }, { photo:”filepath3.jpg”, caption:”This is the caption for pic 3.”, sourceText:”eBay”, sourceLink:”http://www.ebay.com” } }",



"Standard",
"4",
"4 Inline",
"9/16",

"American Vintage Reverse Open-Gear Bass",
"Elephant Ear",
"Large",
"Open",
"Nickel",
"4:1",
"Reverse",
"Split",
"9/16",

"1",
"Round",
"D-G",
"E-A",
"Nickel",
"Polyurethane",
"Gloss",
"Clear",
"Classic",
"Gold w/ Black Outline",
"Classic",
"Black",
"Standard",
"Synthetic Bone",
"NA",
"None",
"NA",

"Single Action",
"Heel",
"Hex Wrench",
"One Piece",
"Maple",
"1",
"Rosewood",
"Nitrocellulose Lacquer",
"Gloss",
"Clear",
"1.5",
"2.5",
"4-Bolt",
"Nickel",
"34",
"Black",
"0",
"NA",
"Dot",
"Clay",
"21",
"Rosewood",
"1",
"N/A",
"N/A",
"1",
"1",
"1",
"7.25",
"Round",
"C",
"Standard",
"0",
"Unknown",

"Alder",
"3-Color Sunburst",
"Nitrocellulose Lacquer",
"0",
"0",
"0",
"Jazz",
"1",
"1",
"0.5",
"Standard",
"4-Saddle American Vintage Bass",
"Nickel",
"Threaded",
"Standard",
"Nickel",
"0",
"NA",
"NA",
"NA",
"NA",
"1",
"Jazz",
"Nickel",
"Top",
"Control Plate",
"Tunnel",
"0",
"NA",
"NA",
"Knurled Flat-Top",
"Nickel",
"NA",
"Solid",
"1.75",
"0",
"NA",
"0",
"NA",
"0",
"0",
"0",
"0",
"0",

"Jazz",
"NA",
"Jazz",
"Custom '60s Single-Coil Jazz Bass®",
"NA",
"Custom '60s Single-Coil Jazz Bass®",
"Single Coil",
"NA",
"Single Coil",
"Black",
"1",
"0",
"VVT",
"NA",
"Chrome",
"Solid",
"1"

)



;